![](https://essentials-assets.s3.eu-west-3.amazonaws.com/M02-SQL/Introduction_to_SQL_and_cloud_computing/logo_chauffeur_prive%CC%81.png)


# Chauffeurs Database


During this exercise, we will assume that we are a private chauffeur company similar to [UBER](https://uber.com). We will call this company "Chauffeurs". We will have to create a structure for the database of the company.


## CREATE TABLE

Chauffeurs must manage its drivers, users and employees and also has data on the cities in which it wants to set up.

1. Create a table for the **Drivers**, it should contain the following columns :
    * ID
    * First name
    * Name
    * Age
    * Address
    * Date permit obtained
    * Number of accidents
    * Average score given by users
2. Create a **Users** table with the following columns
    * ID
    * First name
    * Name
    * Age
    * Average score given by the drivers
3. Create an **Employees** table with the following columns :
    * ID
    * First name
    * Name
    * Number of years of experience
    * Number of kilometres used at Chauffeurs
4. Create a **Cities** table with the following columns
    * ID
    * Name
    * Size (in square kilometres)
    * Number of inhabitants

## INSERT INTO


Let's add values in each table to check that everything works well:

1. Insert 5 rows in **Drivers** (random values are fine ðŸ˜‰)
2. Insert 5 rows in **Users** (random values are fine ðŸ˜‰)
3. Insert 5 rows in **Cities** (random values are fine ðŸ˜‰)
4. Insert 5 rows in **Employees** (random values are fine ðŸ˜‰)

## SELECT


Now, we would like to show that our database is working well to our manager. Let's do some tests:

1. Select all columns in **Drivers**, **Users**, **Employees** and **Cities**.
2. Select all accidents in **Drivers**.
3. Select all the dates when the driver got their driver's license.

## UPDATE

We made a mistake when we inserted our first row in each of our tables.

1. Change the age of the first driver to *28*.
2. Change the first user's first name to *John*.
3. Change the number of years of experience of the first employee to *6 years*.

## ALTER TABLE

We have just realized that it would be useful to have the average number of cars in each city so that we can assess the level of traffic jams and see if it is worthwhile to move there.

1. Add a Number of Cars column to the **Cities** table


## DELETE

One of our employees just left the company, so we have to remove it from our database.

1. Delete the last employee in the Employees table